// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		int randomNumber;
		int countSmaller = 0;
		int countBigger = 0;

		for(int i=0;i<n;i++){
			randomNumber = (int) (Math.random()) + 1;
			if (randomNumber<0.5) {
				countSmaller++;				
			}
			else countBigger++;
		}

		System.out.println("> 0.5:" + countSmaller + "times");
		System.out.println("<= 0.5:" + countBigger + "times");
		System.out.println("Ratio" + countSmaller/countSmaller);

	}
}
